### ISSUE TITLE
Automatically complete install/configuration

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-gogs#1]
See: https://github.com/gogits/gogs/issues/145#issuecomment-42162652

> Change security -> INSTALL_LOCK to true in `custom/conf/app.ini` will omit install page step.

**Comment by geerlingguy** [comment]
Also, when running the latest version of Gogs, I get:

> No custom 'conf/app.ini' found, please go to '/install'

**Comment by rosstimson** [comment]
I'd like to see this feature too.  I'm trying to setup a private Gogs in which I'll disable user registration and use an admin account to add users.  I'd like to use options such as Redis for cache/sessions and Oauth but such settings in `custom/conf/app.ini` will be overwritten when I go through the web based '/install' step and furthermore they are not available to set during the web based install.

The problem is, how can I setup the initial admin user if I set `INSTALL_LOCK = true`?

My current workflow would have to be:
1.  Ansible playbook starts Gogs (+ `custom/conf/app.ini` mounted as a volume) and linked MySQL containers.
2.  The `app.ini` gets overwritten during install and initial admin user creation.
3.  Another Ansible playbook stops Gogs container and starts another linking to the MySQL container that now has an admin user in the DB and mount my final `custom/conf/app.ini`.

I don't know if there is a better way to do this but I can't figure it out so far, the only other alternative seems to be working out the raw sql to add the admin user during the Ansible play and set the `INSTALL_LOCK = true` option.  Two seperate provisioning runs with manual intervention in the middle and a container/service restart **or** raw SQL hackery both seem very wrong.
